### ISSUE TITLE
Multiple WsProvider support for chains

### ISSUE THREAD

**Issue by ap211unitech** [moonbeam-foundation/xcm-sdk#231]
In current chain configuration, We can put only one provider for a chain. but native polkadot API connector can accept an array of multiple providers. It would be great to have this functionality in SDK as well. It would be better for having a reliable connection with blockchain. 

For e.g.  - 

```ts
export const assetHub = new Parachain({
  assetsData: [
    {
      asset: dot,
      decimals: 10,
      id: 0,
    },
    {
      asset: usdt,
      decimals: 6,
      id: 1984,
      palletInstance: 50,
    },
  ],
  ecosystem: Ecosystem.Polkadot,
  genesisHash:
    "0x68d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2f",
  key: "assethub",
  name: "AssetHub",
  parachainId: 1000,
  ss58Format: 42,
  ws: "wss://polkadot-asset-hub-rpc.polkadot.io",  // Only one WS provider
});
```

but Polkadot API connector can support it like this - 

```ts

const apiUrl = ["wss://statemint.public.curie.radiumblock.co/ws", "wss://statemint-rpc.dwellir.com", "wss://statemint.api.onfinality.io/public-ws"]

export async function createApi(apiUrl: string[]): Promise<void> {
  const provider = new WsProvider(apiUrl, RECONNECT_TIME_MS);
  statics.api = new ApiPromise({
    provider,
    runtime: { ...runtime, ...apiTypes.runtime },
    types: { ...types, ...apiTypes.types },
    rpc: { ...rpc, ...apiTypes.rpc },
    signedExtensions: {
      ChargeAssetTxPayment: {
        extrinsic: {
          tip: "Compact<Balance>",
          assetId: "Option<u128>",
        },
        payload: {},
      },
    },
  });
}
```

Would like to know if we can have this feature.

**Comment by ekenigs** [comment]
@ap211unitech hey, sorry for the delayed answer. I think what you are proposing makes sense and I had this in my mind for a while but we could not implement this yet. You can wait until we have time or if you really need this you can submit a PR and we will review it.

**Comment by ekenigs** [comment]
Will be published in this release https://github.com/moonbeam-foundation/xcm-sdk/pull/274
